name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        dotnet-quality: 'ga'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Ensure browsers are installed
      run: pwsh ./tests/XPing365.Sdk.IntegrationTests/bin/Release/net8.0/playwright.ps1 install --with-deps
    - name: Test
      run: dotnet test -c Release --no-build --collect:"XPlat Code Coverage" -l "console;verbosity=normal"
    - name: Coverage
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
      with:
        reports: ./tests/**/coverage.cobertura.xml
        targetdir: coveragereport
        reporttypes: Html;Badges
        assemblyfilters: +XPing365.Sdk.Core;+XPing365.Sdk.Availability
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: CoverageReport
        path: coveragereport
